// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechCartAPI.Data;

#nullable disable

namespace TechCartAPI.Migrations
{
    [DbContext(typeof(TechCartContext))]
    [Migration("20260628040021_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechCartAPI.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            IsActive = true,
                            Name = "Apple"
                        },
                        new
                        {
                            BrandId = 2,
                            IsActive = true,
                            Name = "Samsung"
                        },
                        new
                        {
                            BrandId = 3,
                            IsActive = true,
                            Name = "Sony"
                        },
                        new
                        {
                            BrandId = 4,
                            IsActive = true,
                            Name = "Dell"
                        },
                        new
                        {
                            BrandId = 5,
                            IsActive = true,
                            Name = "OnePlus"
                        },
                        new
                        {
                            BrandId = 6,
                            IsActive = true,
                            Name = "Bose"
                        });
                });

            modelBuilder.Entity("TechCartAPI.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("TechCartAPI.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Mobile phones and accessories",
                            IsActive = true,
                            Name = "Smartphones"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Laptops and notebooks",
                            IsActive = true,
                            Name = "Laptops"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Headphones, speakers, earbuds",
                            IsActive = true,
                            Name = "Audio"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Tablets and iPads",
                            IsActive = true,
                            Name = "Tablets"
                        },
                        new
                        {
                            CategoryId = 5,
                            Description = "Cables, cases, chargers",
                            IsActive = true,
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("TechCartAPI.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TechCartAPI.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("TechCartAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("DiscountPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("SKU")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specifications")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 28, 4, 0, 21, 163, DateTimeKind.Utc).AddTicks(8040),
                            Description = "Apple iPhone 15 Pro with A17 Pro chip",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "iPhone 15 Pro",
                            Price = 134900m,
                            SKU = "APL-IP15P",
                            Stock = 50
                        },
                        new
                        {
                            ProductId = 2,
                            BrandId = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 28, 4, 0, 21, 163, DateTimeKind.Utc).AddTicks(8050),
                            Description = "Samsung flagship with AI features",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Samsung Galaxy S24",
                            Price = 79999m,
                            SKU = "SAM-GS24",
                            Stock = 80
                        },
                        new
                        {
                            ProductId = 3,
                            BrandId = 1,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 28, 4, 0, 21, 163, DateTimeKind.Utc).AddTicks(8050),
                            Description = "Apple MacBook Pro with M3 chip",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "MacBook Pro 14",
                            Price = 198900m,
                            SKU = "APL-MBP14",
                            Stock = 30
                        },
                        new
                        {
                            ProductId = 4,
                            BrandId = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 28, 4, 0, 21, 163, DateTimeKind.Utc).AddTicks(8050),
                            Description = "Dell XPS 15 premium laptop",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Dell XPS 15",
                            Price = 159999m,
                            SKU = "DEL-XPS15",
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 5,
                            BrandId = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 6, 28, 4, 0, 21, 163, DateTimeKind.Utc).AddTicks(8050),
                            Description = "Industry leading noise cancellation",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Sony WH-1000XM5",
                            Price = 29990m,
                            SKU = "SNY-WH1000",
                            Stock = 100
                        },
                        new
                        {
                            ProductId = 6,
                            BrandId = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 6, 28, 4, 0, 21, 163, DateTimeKind.Utc).AddTicks(8050),
                            Description = "Bose premium noise cancelling headphones",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Bose QuietComfort 45",
                            Price = 24990m,
                            SKU = "BSE-QC45",
                            Stock = 75
                        },
                        new
                        {
                            ProductId = 7,
                            BrandId = 1,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 6, 28, 4, 0, 21, 163, DateTimeKind.Utc).AddTicks(8060),
                            Description = "Apple iPad Pro with M2 chip",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "iPad Pro 12.9",
                            Price = 112900m,
                            SKU = "APL-IPADP12",
                            Stock = 40
                        },
                        new
                        {
                            ProductId = 8,
                            BrandId = 2,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 6, 28, 4, 0, 21, 163, DateTimeKind.Utc).AddTicks(8060),
                            Description = "Samsung premium Android tablet",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Samsung Galaxy Tab S9",
                            Price = 72999m,
                            SKU = "SAM-TABS9",
                            Stock = 35
                        },
                        new
                        {
                            ProductId = 9,
                            BrandId = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 28, 4, 0, 21, 163, DateTimeKind.Utc).AddTicks(8060),
                            Description = "OnePlus flagship with Snapdragon 8 Gen 3",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "OnePlus 12",
                            Price = 64999m,
                            SKU = "OP-12",
                            Stock = 60
                        },
                        new
                        {
                            ProductId = 10,
                            BrandId = 1,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 6, 28, 4, 0, 21, 163, DateTimeKind.Utc).AddTicks(8060),
                            Description = "Apple official USB-C braided cable",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Apple USB-C Cable",
                            Price = 1900m,
                            SKU = "APL-USBC",
                            Stock = 500
                        });
                });

            modelBuilder.Entity("TechCartAPI.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TechCartAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Customer");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TechCartAPI.Models.CartItem", b =>
                {
                    b.HasOne("TechCartAPI.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechCartAPI.Models.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechCartAPI.Models.Order", b =>
                {
                    b.HasOne("TechCartAPI.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechCartAPI.Models.OrderItem", b =>
                {
                    b.HasOne("TechCartAPI.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechCartAPI.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TechCartAPI.Models.Product", b =>
                {
                    b.HasOne("TechCartAPI.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechCartAPI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TechCartAPI.Models.Review", b =>
                {
                    b.HasOne("TechCartAPI.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechCartAPI.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechCartAPI.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TechCartAPI.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TechCartAPI.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("TechCartAPI.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("TechCartAPI.Models.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
